version: "3"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: my-rds-instance.cfeu2awuicm1.us-west-2.rds.amazonaws.com
      WORDPRESS_DB_USER: vijaya
      WORDPRESS_DB_PASSWORD: Study2024
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - wordpress_data:/var/www/html

volumes:
  wordpress_data: